name: easdk

type: node

up:
  - railgun
  - node:
      version: v8.9.4
      yarn: true
      packages:
        - .

commands:
  console: node
  server: yarn start

open:
  app: https://easdk.myshopify.io
